/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import arquivo.Arquivos;
import static arquivo.Arquivos.moverArquivos;
import extensao_arquivos.ExtensaoArquivos;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import mensagens.MensagemUsuario;

/**
 *
 * @author Andre
 */
public class TelaTeste extends javax.swing.JFrame {

    private byte[] Arquivo;
    private File file;
    private Arquivos arquivos;
    private ExtensaoArquivos extensoes = new ExtensaoArquivos();

    /**
     * Creates new form TelaTeste
     */
    public TelaTeste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSecionarArquivo = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btMoverArquivo = new javax.swing.JButton();
        lbDestino = new javax.swing.JLabel();
        lbOrigem1 = new javax.swing.JLabel();
        btDeletarArquivo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbNmeArquivo = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        btBusca = new javax.swing.JButton();
        cbLocal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btSecionarArquivo.setText("Selecionar um arquivo...");
        btSecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSecionarArquivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Origem");

        jLabel2.setText("Destino:");

        btMoverArquivo.setText("Mover para..");
        btMoverArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMoverArquivoActionPerformed(evt);
            }
        });

        btDeletarArquivo.setText("Deletar Arquivo");
        btDeletarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarArquivoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome");

        btBusca.setText("Busca...");
        btBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaActionPerformed(evt);
            }
        });

        cbLocal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C:\\\\Teste" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDeletarArquivo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNmeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSecionarArquivo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btMoverArquivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbOrigem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cbLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOrigem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSecionarArquivo)
                        .addComponent(jLabel1)))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btMoverArquivo)
                        .addComponent(jLabel2)))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNmeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btDeletarArquivo)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBusca)
                    .addComponent(cbLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMoverArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMoverArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMoverArquivoActionPerformed

    private void btSecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSecionarArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSecionarArquivoActionPerformed

    private void btDeletarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDeletarArquivoActionPerformed

    private void btBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaActionPerformed
        // TODO add your handling code here:
        btBusca.setEnabled(false);
        int tamMax = extensoes.getExtensoesFotos().size() + extensoes.getExtensoesMusica().size() + extensoes.getExtensoesVideos().size();
       tamMax = 3;
              
        jProgressBar1.setMaximum(0);
        jProgressBar1.setMaximum(tamMax);
        new Thread() {
              int  cont = 0;
            public void run() {

                
                    Arquivos.moverArquivoTipoMusica(new File("C:\\Users\\developer"), new File("c:\\Destino"));
                    cont++;
                    jProgressBar1.setValue(cont);
                
                
               
                    Arquivos.moverArquivoTipoFotos(new File("C:\\Users\\developer"), new File("c:\\Destino"));
                    cont++;
                    jProgressBar1.setValue(cont);
               
                
              
                   Arquivos.moverArquivoTipoVideo(new File("C:\\Users\\developer"), new File("c:\\Destino"));
                    cont++;
                    jProgressBar1.setValue(cont);
               
            }

        }.start();

        btBusca.setEnabled(true);

    }//GEN-LAST:event_btBuscaActionPerformed

    private void abrirChoose() {
        try {
            JFileChooser abrirArquivo = new JFileChooser();
            abrirArquivo.setDialogTitle("Procura Arquivo");
            //FileNameExtensionFilter extecaoPermitida = new FileNameExtensionFilter("Imagem", "jpg"); // permitir somente as esteções jpg e png
            //abrirArquivo.setFileFilter(extecaoPermitida);
            int foiSelecionadoArquivo = abrirArquivo.showOpenDialog(null);
            if (foiSelecionadoArquivo != JFileChooser.APPROVE_OPTION) {
                MensagemUsuario.mensagemAviso("Você não selecionou nem uma Imagem!");
                return;
            }

            File pegaArquivo = abrirArquivo.getSelectedFile();
            Arquivo = Arquivos.coverterArquivoEmArrayDeByte(pegaArquivo);

            lbOrigem1.setText(pegaArquivo.getAbsolutePath());
            lbNmeArquivo.setText(pegaArquivo.getName());

        } catch (Exception e) {
            MensagemUsuario.mensagemErro(e.getMessage());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBusca;
    private javax.swing.JButton btDeletarArquivo;
    private javax.swing.JButton btMoverArquivo;
    private javax.swing.JToggleButton btSecionarArquivo;
    private javax.swing.JComboBox<String> cbLocal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lbDestino;
    private javax.swing.JLabel lbNmeArquivo;
    private javax.swing.JLabel lbOrigem1;
    // End of variables declaration//GEN-END:variables
}
